config/routes.rb
Rails.application.routes.draw do
  
  
  get 'home/index'      
  get 'home/show'

  root to: "home#index"
  

  # devise_for :users, controllers: {
  #   registrations: "users/registrations",
  # }
  devise_for :users


  resources :users do
    get :search, on: :collection
    member do
      get 'userhowto'
      get 'usernote'

      get :following, :followers
    end
  end

  resources :relationships, only: [:create, :destroy]


  resources :how_tos do
    resources :fights, only: [:create, :destroy]
    resources :advices, only: [:create, :destroy]
  end
  
  resources :spots do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end

  resources :notes do
    resources :archives, only: [:create, :destroy]
    resources :questions, only: [:create, :destroy]
  end
  

  


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/advice.rb
class Advice < ApplicationRecord
  belongs_to :user
  belongs_to :how_to

  validates :content, presence: true
end

app/models/archive.rb
class Archive < ApplicationRecord
  belongs_to :note
  belongs_to :user
  validates_uniqueness_of :note_id, scope: :user_id
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :spot

  validates :rate, presence: true
end

app/models/fight.rb
class Fight < ApplicationRecord
  belongs_to :how_to
  belongs_to :user

  validates_uniqueness_of :how_to_id, scope: :user_id
end

app/models/hashtag.rb
class Hashtag < ApplicationRecord

end

app/models/hashtag_note.rb
class HashtagNote < ApplicationRecord

end

app/models/home.rb
class Home < ApplicationRecord
  default_scope -> { order(created_at: :desc) }
end

app/models/how_to.rb
class HowTo < ApplicationRecord
  default_scope -> { order(created_at: :desc) }

  mount_uploader :image, ImageUploader
  mount_uploader :video, VideoUploader

  belongs_to :user

  has_many :fights, dependent: :destroy
  has_many :fought_users, through: :fights, source: :user
  
  has_many :advices, dependent: :destroy

  validates :title, presence: true
  validates :video, presence: true
  validates :content, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :spot
  belongs_to :user

  validates_uniqueness_of :spot_id, scope: :user_id
end

app/models/map.rb
class Map < ApplicationRecord
  
end

app/models/note.rb
class Note < ApplicationRecord
  has_rich_text :content

  belongs_to :user

  has_many :archives, dependent: :destroy
  has_many :archived_users, through: :archives, source: :user
  has_many :questions, dependent: :destroy

  validates :content, presence: true
  validates :title, presence: true
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  belongs_to :note

  validates :content, presence: true
end

app/models/relationship.rb
class Relationship < ApplicationRecord

  belongs_to :follower, class_name: "User"
  belongs_to :following, class_name: "User"
  validates :follower_id, presence: true
  validates :following_id, presence: true

end

app/models/spot.rb
class Spot < ApplicationRecord
  default_scope -> { order(created_at: :desc) }
  
  mount_uploader :image, ImageUploader
  mount_uploader :image2, ImageUploader
  mount_uploader :image3, ImageUploader

  belongs_to :user

  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user

  has_many :comments, dependent: :destroy

  has_many :post_tag_relations, dependent: :destroy
  has_many :tags, through: :post_tag_relations, dependent: :destroy


  validates :title, presence: true




end

app/models/spot_image.rb
class SpotImage < ApplicationRecord

  

end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :post_tag_relations, dependent: :destroy
  has_many :spots, through: :post_tag_relations, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :profile_image, ImageUploader
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :spots, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_spots, through: :likes, source: :spot
  has_many :comments, dependent: :destroy
  def already_liked?(spot)
    self.likes.exists?(spot_id: spot.id)
  end

  has_many :how_tos, dependent: :destroy
  has_many :fights, dependent: :destroy
  has_many :fought_how_tos, through: :fights, source: :how_to
  has_many :advices, dependent: :destroy
  def already_fought?(how_to)
    self.fights.exists?(how_to_id: how_to.id)
  end

  has_many :notes, dependent: :destroy
  has_many :archives, dependent: :destroy
  has_many :archived_notes, through: :archives, source: :note
  has_many :questions, dependent: :destroy
  def already_archived?(note)
    self.archives.exists?(note_id: note.id)
  end


  has_many :following_relationships, foreign_key: "follower_id", class_name: "Relationship", dependent: :destroy
  has_many :followings, through: :following_relationships

  has_many :follower_relationships, foreign_key: "following_id", class_name: "Relationship", dependent: :destroy
  has_many :followers, through: :follower_relationships

  def following?(other_user)
    following_relationships.find_by(following_id: other_user.id)
  end

  def follow!(other_user)
    following_relationships.create!(following_id: other_user.id)
  end

  def unfollow!(other_user)
    following_relationships.find_by(following_id: other_user.id).destroy
  end



  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable

  validates :profile, length: { maximum: 30 } 
  # validates :email, uniqueness: true
  validates :username, uniqueness: true

  # def email_required?
  #   false
  # end

  # def email_changed?
  #   false
  # end
  

end

app/controllers/spots_controller.rb
class SpotsController < ApplicationController
  layout 'spot'

  def index
    if params[:search] == nil
      @spots= Spot.all.page(params[:page]).per(6)
    elsif params[:search] == ''
      @spots= Spot.all.page(params[:page]).per(6)
    else
      @spots = Spot.where("title LIKE ? ",'%' + params[:search] + '%').or(Spot.where("text LIKE ? ", "%" + params[:search] + "%")).page(params[:page]).per(6)
    end
    @spots = params[:tag_id].present? ? Tag.find(params[:tag_id]).spots : Spot.all.page(params[:page]).per(6)
  end

  def new
    @spot = Spot.new
  end

  def create
    @spot = Spot.new(spot_params)
    @spot.user_id = current_user.id
    if @spot.save
      redirect_to :action => "index"
    else
      render "new"
    end
  end

  def show
    @spot = Spot.find(params[:id])
    @comments = @spot.comments
    @comment = Comment.new
  end

  def edit
    @spot = Spot.find(params[:id])
  end

  def update
    @spot = Spot.find(params[:id])
    if @spot.update(spot_params)
      redirect_to :action => "show", :id => @spot.id
    else
      render "edit"
    end
  end

  def destroy
    spot = Spot.find(params[:id])
    spot.destroy
    redirect_to action: :index
  end


  private

  def spot_params
    params.require(:spot).permit(:title, :text, :image, :image2, :image3, :remove_image, :remove_image2, :remove_image3, :lat, :lng, tag_ids: [])
  end
  
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/notes_helper.rb
module NotesHelper
  
end

app/helpers/spots_helper.rb
module SpotsHelper
  def getPercent(number) 
    if number.present?
      calPercent = number/5.to_f * 100
      percent = calPercent.round
      return percent.to_s
    else
      return 0
    end
  end
end

app/views/spots/edit.html.erb
<div class="form-container">
  <div class="backform">
    <%= link_to "＜戻る", spot_path %>
  </div>
  <div class="form-contents">
    <%= form_with(model: @spot, local: true) do |f| %>
    <%= render 'layouts/error_messages', model: f.object %>
      <div class="title-field-container">
        <div class="form-title">
          <%= f.label :title %>
        </div>
        <div class="title-field">
          <%= f.text_field :title, :size => 140 %>
        </div>
      </div>
      <div class="content-field-container">
        <div class="form-content">
          <%= f.label :text %>
        </div>
        <div class="content-field">
            <%= f.text_area :text, :size => "67x5" %>
        </div>

      <div class="form-image-container">
        <div class="video-container">
          <div class="form-video">
            <%= f.label :image1 %>
          </div>
            <!-- <%= f.file_field :image1, id: :spot_img %> -->
            <%= f.label :image, "画像を選択", class: "spot_image-btn" %>
            <%= f.file_field :image, class: "image_form" %>
            <p><%= f.check_box :remove_image %>クリア</p>
              <% if @spot.image.present? %>
                <%= image_tag @spot.image_url, size: "120x80" %>
              <% else %>
                <%= image_tag 'Photo.jpg', size: "120x80" %>
              <% end %>
          </div>
        
          <div class="video-container">
            <div class="form-video">
              <%= f.label :image2 %>
            </div>
            
              <!-- <%= f.file_field :image2, id: :spot_img %> -->
              <%= f.label :image2, "画像を選択", class: "spot_image-btn" %>
              <%= f.file_field :image2, class: "image_form" %>
              <p><%= f.check_box :remove_image2 %>クリア</p>
                <% if @spot.image2.present? %>
                  <%= image_tag @spot.image2_url, size: "120x80" %>
                <% else %>
                  <%= image_tag 'Photo.jpg', size: "120x80" %>
                <% end %>
            </div>

          <div class="video-container">
            <div class="form-video">
              <%= f.label :image3 %>
            </div>
            <!-- <%= f.file_field :image3, id: :spot_img %> -->
            <%= f.label :image3, "画像を選択", class: "spot_image-btn" %>
            <%= f.file_field :image3, class: "image_form" %>
            <p><%= f.check_box :remove_image3 %>クリア</p>
              <% if @spot.image3.present? %>
                <%= image_tag @spot.image3_url, size: "120x80" %>
              <% else %>
                <%= image_tag 'Photo.jpg', size: "120x80" %>
              <% end %>
          </div>
        </div>

          <div class='form-tag-group'>
            <div class="form-tag-name">
              <%= f.label :Section・Item %>
            </div>
            <div class="tag-list">
              <%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :name) do |tag| %>
                  <div class='form-check'>
                    <%= tag.label class: 'form-check-label' do %>
                        <%= tag.check_box class: 'form-check-input' %>
                        <%= tag.text %>
                    <% end %>
                  </div>
              <% end %>
            </div>
          </div>

          <div class='lat-lng'>
            <%= f.label :lat,"緯度" %>
            <%= f.text_field :lat,:value =>"緯度", id: :lat %>
            <%= f.label :lng,"経度" %>
            <%= f.text_field :lng,:value =>"経度", id: :lng %>
          </div>

          



      <div class="form-map">
        <h3>Map</h3>
          
          <input id="address" type="textbox" value="スポット付近">
          <input type="button" value="検索" onclick="codeAddress()">
          <h4>マーカーをドラック＆ドロップで位置の調整ができます。</h4>
          <div id='map'></div>
          
          <style>
          #map {
            height: 300px;
            width: 600px;
          }
          </style>
          
          <script>
          //初期マップの設定
          let map
          let marker
          function initMap(){
            geocoder = new google.maps.Geocoder()
          
            map = new google.maps.Map(document.getElementById('map'), {
              center:  {lat: 36.3904768, lng:137.8992582}, 
              zoom: 6.5,
          
            });
          }
          
          //検索後のマップ作成
          let geocoder
          let aft
          function codeAddress(){
            let inputAddress = document.getElementById('address').value;
            geocoder.geocode( { 'address': inputAddress}, function(results, status) {
              if (status == 'OK') {
                  //マーカーが複数できないようにする
                  if (aft == true){
                      marker.setMap(null);
                  }
          
                  //新しくマーカーを作成する
                  map.setCenter(results[0].geometry.location);
                      marker = new google.maps.Marker({
                      map: map,
                      position: results[0].geometry.location,
                      draggable: true // ドラッグ可能にする
                  });
          
                  //二度目以降か判断
                  aft = true
          
                  //検索した時に緯度経度を入力する
                  document.getElementById('lat').value = results[0].geometry.location.lat();
                  document.getElementById('lng').value = results[0].geometry.location.lng();
          
                  // マーカーのドロップ（ドラッグ終了）時のイベント
                  google.maps.event.addListener( marker, 'dragend', function(ev){
                      // イベントの引数evの、プロパティ.latLngが緯度経度
                      document.getElementById('lat').value = ev.latLng.lat();
                      // results[0].geometry.location.lat() = ev.latLng.lat();
                      document.getElementById('lng').value = ev.latLng.lng();
                      // results[0].geometry.location.lng() = ev.latLng.lng();
                  });
              } else {
                alert('該当する結果がありませんでした：' + status);
              }
            });   
          }
          
          </script>
          <script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_MAP_API_KEY'] %>&callback=initMap" async defer></script>
      </div>
        
      <%= f.submit "　　　投稿　　　" %>
    <% end %>    
  </div>
</div>

app/views/spots/index.html.erb
<div class="main">
  <div class="main-top">
    <div class="search">

      <%= form_tag({controller:"spots",action:"index"}, method: :get) do %>
        <%= text_field_tag :search %>
        <%= button_tag :type => "submit", :class =>"search-btn" do %>
          <i class="fas fa-search"></i>
        <% end %>
      <% end %>
    </div>
    <div class="tag-search">
      <%= form_tag spots_path, method: :get, class: 'boards__searchForm' do %>
        <%= select_tag :tag_id,
                      options_from_collection_for_select(Tag.all, :id, :name, params[:tag_id]),
                      {
                        prompt: 'セクション',
                        onchange: 'submit(this.form);'
                      }
                      
        %>
      <% end %>
    </div>
    <div class="new">
        <% if user_signed_in? %>
          <%= link_to new_spot_path do %>
            <i class="gg-add-r"></i>
          <% end %>
        <% else %>
          <%= link_to new_user_session_path do %>
            <i class="gg-add-r"></i>
          <% end %>
        <% end %>
    </div>
  </div>
      <div class="spots-container">
        <% @spots.each do |t| %>
          <div class="spots-item">
            <div class="spot-box">
                <div class="spot-image-container">
                  <div class="spot-image">
                    <a href="/spots/<%= t.id %>">
                      <% if t.image.present? %>
                        <%= image_tag t.image_url, size: "90%x300" %>
                      <% else %>
                        <%= image_tag 'Photo.jpg', size: "90%x250" %>
                      <% end %>
                    </a>
                  </div>
                </div>
              <div class="spot-details">
                <div class="spot-text">
                  <div class="spot-text-top">
                    <div class="user-container">
                      <div class="userimage">
                        <% if t.user.profile_image.present? %>
                          <a href="/users/<%= t.user.id %>"><%= image_tag t.user.profile_image_url, size: "30x30" %></a>
                        <% else %>
                          <a href="/users/<%= t.user.id %>"><%= image_tag 'usericon.jpg' , size: "30x30" %></a>
                        <% end %>
                      </div>
                      <div class="username">
                        <a href="/users/<%= t.user.id %>"><%= t.user.username %></a>
                      </div>
                    </div>
                    
                    <div class="spot-like">
                        <% if user_signed_in? %>
                          <% if current_user.already_liked?(t) %>
                            <%= link_to spot_like_path(id: t.id, spot_id: t.id), method: :delete do %>
                              <i class="fas fa-heart"></i><%= t.likes.count %>
                            <% end %>
                          <% else %>
                            <%= link_to spot_likes_path(id: t.id, spot_id: t.id), method: :post do %>
                              <i class="far fa-heart"></i><%= t.likes.count %>
                            <% end %>
                          <% end %>
                        <% else %>
                          <%= link_to new_user_session_path do %>
                            <%= link_to new_user_session_path do %>
                              <i class="far fa-heart"></i><%= t.likes.count %>
                            <% end %>
                          <% end %>
                        <% end %>
                    </div>
                  </div>  
                  <div class="spot-text-list">
                    <div class="text-title">
                      <a href="/spots/<%= t.id %>"><%= t.title %></a>
                    </div>
                    <div class="text-content">
                      <a href="/spots/<%= t.id %>"><%= t.text %></a>
                    </div>
                  </div>  
                </div>
                
              </div>
            </div>
          </div>
          <!-- <%= link_to "削除する", spot_path(t.id), method: :delete %> -->
          
        <% end %>      
      </div>
    

</div>

app/views/spots/new.html.erb
<div class="form-container">
  <div class="backform">
    <%= link_to "＜戻る", spots_path %>
  </div>
  <div class="form-contents">
    <%= form_with(model: @spot, local: true) do |f| %>
    <%= render 'layouts/error_messages', model: f.object %>
      <div class="title-field-container">
        <div class="form-title">
          <%= f.label :title %>
        </div>
        <div class="title-field">
          <%= f.text_field :title, :size => 140 %>
        </div>
      </div>
      <div class="content-field-container">
        <div class="form-content">
          <%= f.label :text %>
        </div>
        <div class="content-field">
            <%= f.text_area :text, :size => "67x5" %>
        </div>
      </div>
      <div class="video-container">
          <div class="form-video">
            <%= f.label :image1 %>
          </div>
          
          <!-- <%= f.file_field :image, id: :spot_img %> -->
          <%= f.label :image, "画像を選択", class: "spot_image-btn" %>
          <%= f.file_field :image, class: "image_form" %>
          <p><%= f.check_box :remove_image %>クリア</p>

          <div class="form-video">
            <%= f.label :image2 %>
          </div>
          <!-- <%= f.file_field :image2, id: :spot_img %> -->
          <%= f.label :image2, "画像を選択", class: "spot_image-btn" %>
          <%= f.file_field :image2, class: "image_form" %>
          <p><%= f.check_box :remove_image2 %>クリア</p>
            
          <div class="form-video">
            <%= f.label :image3 %>
          </div>
          <!-- <%= f.file_field :image3, id: :spot_img %> -->
          <%= f.label :image3, "画像を選択", class: "spot_image-btn" %>
          <%= f.file_field :image3, class: "image_form" %>
          <p><%= f.check_box :remove_image3 %>クリア</p>
            
      </div>

          <div class='form-tag-group'>
            <div class="form-tag-name">
              <%= f.label :Section・Item %>
            </div>
            <div class="tag-list">
              <%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :name) do |tag| %>
                  <div class='form-check'>
                    <%= tag.label class: 'form-check-label' do %>
                        <%= tag.check_box class: 'form-check-input' %>
                        <%= tag.text %>
                    <% end %>
                  </div>
              <% end %>
            </div>
          </div>

          <div class='lat-lng'>
            <%= f.label :lat,"緯度" %>
            <%= f.text_field :lat,:value =>"緯度", id: :lat %>
            <%= f.label :lng,"経度" %>
            <%= f.text_field :lng,:value =>"経度", id: :lng %>
          </div>

          



      <div class="form-map">
        <h3>Map</h3>
          
          <input id="address" type="textbox" value="スポット付近">
          <input type="button" value="検索" onclick="codeAddress()">
          <h4>マーカーをドラック＆ドロップで位置の調整ができます。</h4>
          <div id='map'></div>
          
          <style>
          #map {
            height: 300px;
            width: 600px;
          }
          </style>
          
          <script>
          //初期マップの設定
          let map
          let marker
          function initMap(){
            geocoder = new google.maps.Geocoder()
          
            map = new google.maps.Map(document.getElementById('map'), {
              center:  {lat: 36.3904768, lng:137.8992582}, 
              zoom: 6.5,
          
            });
          }
          
          //検索後のマップ作成
          let geocoder
          let aft
          function codeAddress(){
            let inputAddress = document.getElementById('address').value;
            geocoder.geocode( { 'address': inputAddress}, function(results, status) {
              if (status == 'OK') {
                  //マーカーが複数できないようにする
                  if (aft == true){
                      marker.setMap(null);
                  }
          
                  //新しくマーカーを作成する
                  map.setCenter(results[0].geometry.location);
                      marker = new google.maps.Marker({
                      map: map,
                      position: results[0].geometry.location,
                      draggable: true // ドラッグ可能にする
                  });
          
                  //二度目以降か判断
                  aft = true
          
                  //検索した時に緯度経度を入力する
                  document.getElementById('lat').value = results[0].geometry.location.lat();
                  document.getElementById('lng').value = results[0].geometry.location.lng();
          
                  // マーカーのドロップ（ドラッグ終了）時のイベント
                  google.maps.event.addListener( marker, 'dragend', function(ev){
                      // イベントの引数evの、プロパティ.latLngが緯度経度
                      document.getElementById('lat').value = ev.latLng.lat();
                      // results[0].geometry.location.lat() = ev.latLng.lat();
                      document.getElementById('lng').value = ev.latLng.lng();
                      // results[0].geometry.location.lng() = ev.latLng.lng();
                  });
              } else {
                alert('該当する結果がありませんでした：' + status);
              }
            });   
          }
          
          </script>
          <script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_MAP_API_KEY'] %>&callback=initMap" async defer></script>
      </div>
        
      <%= f.submit "　　　投稿　　　" %>
    <% end %>
  </div>
</div>

app/views/spots/show.html.erb
<div class="spot-show">
    <div class="spot-show-container">
        <div class="spot-show-contents">
          <div class="show-top">
            <div class="show-top-left">
              <div class="show-text">
                <div class="show-user">
                  <div class="show-userimage">
                    <% if @spot.user.profile_image.present? %>
                      <a href="/users/<%= @spot.user.id %>"><%= image_tag @spot.user.profile_image_url, size: "30x30" %></a>
                    <% else %>
                      <a href="/users/<%= @spot.user.id %>"><%= image_tag 'usericon.jpg' , size: "30x30" %></a>
                    <% end %>
                  </div>
                  <div class="show-username">
                    <a href="/users/<%= @spot.user.id %>"><%= @spot.user.username %></a>
                  </div>
                </div>
                <div class="show-title">
                  <%= @spot.title %>
                </div>
                <div class="to-rate">
                  <nav><a href="#comment-form">★評価する</a>
                </div>
              </div>
            </div>
            <div class="show-top-right">
              <% if user_signed_in? %>
                <% if current_user.already_liked?(@spot) %>
                  <%= link_to spot_like_path(@spot), method: :delete do %>
                    <i class="fas fa-heart"></i><%= @spot.likes.count %>
                  <% end %>
                <% else %>
                  <%= link_to spot_likes_path(@spot), method: :post do %>
                    <i class="far fa-heart"></i><%= @spot.likes.count %>
                  <% end %>
                <% end %>
              <% else %>
                <%= link_to new_user_session_path do %>
                  <i class="far fa-heart"></i><%= @spot.likes.count %>
                <% end %>
              <% end %>
            </div>
          </div>
          <div class="show-image">
              <!-- Swiper -->
            <div class="swiper-container">
              <div class="swiper-wrapper">
                <div class="swiper-slide">
                  <% if @spot.image.present? %>
                    <%= image_tag @spot.image_url, size: "100%x450px" %>
                  <% else %>
                    <%= image_tag 'Photo.jpg' %>
                  <% end %>
                </div>
                <div class="swiper-slide">
                  <% if @spot.image2.present? %>
                    <%= image_tag @spot.image2_url, size: "100%x450px" %>
                  <% else %>
                    <%= image_tag 'Photo.jpg' %>
                  <% end %>
                </div>
                <div class="swiper-slide">
                  <% if @spot.image3.present? %>
                    <%= image_tag @spot.image3_url, size: "100%x450px" %>
                  <% else %>
                    <%= image_tag 'Photo.jpg' %>
                  <% end %>
                </div>
                
              </div>
              <!-- Add Arrows -->
              <div class="swiper-button-next"></div>
              <div class="swiper-button-prev"></div>
            </div>
            
          </div>
          <div class="show-details">
            <div class="show-details-top">
              <h3>スポット情報</h3>
              <div class="show-details-right">
                <% if user_signed_in? %>
                  <%= link_to "+ 情報を追加する", edit_spot_path %>
                <% else %>
                  <%= link_to "+ 情報を追加する", new_user_session_path %>
                <% end %>
              </div>
            </div>
            <div class="show-details-container">
              <div class="details-text">
                  <%= simple_format(@spot.text) %>
              </div>
              <div class="details-tag">
                <h2>セクション</h2>
                <div class="details-tag-content">
                  <% @spot.tags.each do |tag| %>
                    <div class="tag-name">
                      <%= tag.name %>
                    </div>
                  <% end %>
                </div>
              </div>
            </div>  
          </div>
        </div>

        <div id='map'></div>

        <!-- js部分 -->
        <script>
        //初期マップの設定
        let map
        let marker
        function initMap(){
          geocoder = new google.maps.Geocoder()

          map = new google.maps.Map(document.getElementById('map'), {
            center:  {lat: <%= @spot.lat %>, lng: <%= @spot.lng %>},
            zoom: 15,
          });

          marker = new google.maps.Marker({
            position:  {lat: <%= @spot.lat %>, lng: <%= @spot.lng %>},
            map: map
          });
        }
        </script>
        <script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_MAP_API_KEY'] %>&callback=initMap" async defer></script>
                  

          <!-- <%= link_to "削除する", spot_path(@spot.id), method: :delete %> -->
            
          


      
        <div class="comment-wrapper">
          <p>レビュー</p>
          <div class="comment-contents">
            <% @comments.each do |c| %>
              <div class="comment-show">
                <div class="comment-left">
                  <div class="comment-user">
                    <div class="comment-userimage">
                      <% if @spot.user.profile_image.present? %>
                        <a href="/users/<%= @spot.user.id %>"><%= image_tag c.user.profile_image_url, size: "25x25" %></a>
                      <% else %>
                        <a href="/users/<%= @spot.user.id %>"><%= image_tag 'usericon.jpg' , size: "25x25" %></a>
                      <% end %>
                    </div>
                    <div class="comment-username"><a href="/users/<%= @spot.user.id %>"><%= c.user.username unless c.user.blank? %></a></div>
                  </div>
                  <div class="comment-ster-rate">
                    <span class="star-rating">
                      <span class="star-rating-front" style="width: <%= getPercent(c.rate) %>%;">★★★★★</span>
                      <span class="star-rating-back">★★★★★</span>
                    </span>
                  </div>
                  <div class="comment-body">
                    <%= c.content %>
                  </div>
                </div>
                <div class="comment-right">
                  <div class="comment-delete">
                    <% if user_signed_in? && current_user.id == c.user_id %>  
                      <%= link_to '削除', spot_comment_path(@spot, c), method: :delete %>
                    <% end %>
                  </div>
                </div>
              </div>
            <% end %>
            <div id="comment-form">
              <%= form_with(model: [@spot, @comment], local: true) do |f| %>
                <div class="post_form">
                  <%= f.radio_button :rate, 5 ,id: 'star1'%>
                  <label for="star1">★</label>
                  
                  <%= f.radio_button :rate, 4 ,id: 'star2'%>
                  <label for="star2">★</label>
                  
                  <%= f.radio_button :rate, 3 ,id: 'star3'%>
                  <label for="star3">★</label>
                  
                  <%= f.radio_button :rate, 2 ,id: 'star4'%>
                  <label for="star4">★</label>
                  
                  <%= f.radio_button :rate, 1 ,id: 'star5'%>
                  <label for="star5">★</label>
                </div>
                <%= f.text_area :content, size: "60x2" %>
                <div class="show-button">
                  <% if user_signed_in? %>
                    <%= button_tag type: "submit" do %>
                      <i class="far fa-comments"></i> 評価する
                    <% end %>
                  <% else %>
                    <%= link_to "評価する", new_user_session_path %>
                  <% end %>
                </div>
              <% end %>
            </div>
          </div>
        </div>
    </div>

</div>