config/routes.rb
Rails.application.routes.draw do
  
  
  get 'home/index'      
  get 'home/show'

  root to: "home#index"
  

  # devise_for :users, controllers: {
  #   registrations: "users/registrations",
  # }
  devise_for :users


  resources :users do
    get :search, on: :collection
    member do
      get 'userhowto'
      get 'usernote'

      get :following, :followers
    end
  end

  resources :relationships, only: [:create, :destroy]


  resources :how_tos do
    resources :fights, only: [:create, :destroy]
    resources :advices, only: [:create, :destroy]
  end
  
  resources :spots do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end

  resources :notes do
    resources :archives, only: [:create, :destroy]
    resources :questions, only: [:create, :destroy]
  end
  

  


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/advice.rb
class Advice < ApplicationRecord
  belongs_to :user
  belongs_to :how_to

  validates :content, presence: true
end

app/models/archive.rb
class Archive < ApplicationRecord
  belongs_to :note
  belongs_to :user
  validates_uniqueness_of :note_id, scope: :user_id
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :spot

  validates :rate, presence: true
end

app/models/fight.rb
class Fight < ApplicationRecord
  belongs_to :how_to
  belongs_to :user

  validates_uniqueness_of :how_to_id, scope: :user_id
end

app/models/hashtag.rb
class Hashtag < ApplicationRecord

end

app/models/hashtag_note.rb
class HashtagNote < ApplicationRecord

end

app/models/home.rb
class Home < ApplicationRecord
  default_scope -> { order(created_at: :desc) }
end

app/models/how_to.rb
class HowTo < ApplicationRecord
  default_scope -> { order(created_at: :desc) }

  mount_uploader :image, ImageUploader
  mount_uploader :video, VideoUploader

  belongs_to :user

  has_many :fights, dependent: :destroy
  has_many :fought_users, through: :fights, source: :user
  
  has_many :advices, dependent: :destroy

  validates :title, presence: true
  validates :video, presence: true
  validates :content, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :spot
  belongs_to :user

  validates_uniqueness_of :spot_id, scope: :user_id
end

app/models/map.rb
class Map < ApplicationRecord
  
end

app/models/note.rb
class Note < ApplicationRecord
  has_rich_text :content

  belongs_to :user

  has_many :archives, dependent: :destroy
  has_many :archived_users, through: :archives, source: :user
  has_many :questions, dependent: :destroy

  validates :content, presence: true
  validates :title, presence: true
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  belongs_to :note

  validates :content, presence: true
end

app/models/relationship.rb
class Relationship < ApplicationRecord

  belongs_to :follower, class_name: "User"
  belongs_to :following, class_name: "User"
  validates :follower_id, presence: true
  validates :following_id, presence: true

end

app/models/spot.rb
class Spot < ApplicationRecord
  default_scope -> { order(created_at: :desc) }
  
  mount_uploader :image, ImageUploader
  mount_uploader :image2, ImageUploader
  mount_uploader :image3, ImageUploader

  belongs_to :user

  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user

  has_many :comments, dependent: :destroy

  has_many :post_tag_relations, dependent: :destroy
  has_many :tags, through: :post_tag_relations, dependent: :destroy


  validates :title, presence: true




end

app/models/spot_image.rb
class SpotImage < ApplicationRecord

  

end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :post_tag_relations, dependent: :destroy
  has_many :spots, through: :post_tag_relations, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :profile_image, ImageUploader
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :spots, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_spots, through: :likes, source: :spot
  has_many :comments, dependent: :destroy
  def already_liked?(spot)
    self.likes.exists?(spot_id: spot.id)
  end

  has_many :how_tos, dependent: :destroy
  has_many :fights, dependent: :destroy
  has_many :fought_how_tos, through: :fights, source: :how_to
  has_many :advices, dependent: :destroy
  def already_fought?(how_to)
    self.fights.exists?(how_to_id: how_to.id)
  end

  has_many :notes, dependent: :destroy
  has_many :archives, dependent: :destroy
  has_many :archived_notes, through: :archives, source: :note
  has_many :questions, dependent: :destroy
  def already_archived?(note)
    self.archives.exists?(note_id: note.id)
  end


  has_many :following_relationships, foreign_key: "follower_id", class_name: "Relationship", dependent: :destroy
  has_many :followings, through: :following_relationships

  has_many :follower_relationships, foreign_key: "following_id", class_name: "Relationship", dependent: :destroy
  has_many :followers, through: :follower_relationships

  def following?(other_user)
    following_relationships.find_by(following_id: other_user.id)
  end

  def follow!(other_user)
    following_relationships.create!(following_id: other_user.id)
  end

  def unfollow!(other_user)
    following_relationships.find_by(following_id: other_user.id).destroy
  end



  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable

  validates :profile, length: { maximum: 30 } 
  # validates :email, uniqueness: true
  validates :username, uniqueness: true

  # def email_required?
  #   false
  # end

  # def email_changed?
  #   false
  # end
  

end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  layout 'note'

  def index
    if params[:search] == nil
      @notes= Note.all.page(params[:page]).per(20)
    elsif params[:search] == ''
      @notes= Note.all.page(params[:page]).per(20)
    else
      @notes = Note.where("title LIKE ? ",'%' + params[:search] + '%').page(params[:page]).per(20)
    end
  end

  def new
    @note = Note.new
  end

  def create
    @note = Note.new(note_params)
    @note.user_id = current_user.id
    if @note.save
      redirect_to :action => "index"
    else
      render "new"
    end
  end

  def show
    @note = Note.find(params[:id])
    @questions = @note.questions
    @question = Question.new
  end

  def edit
    @note = Note.find(params[:id])
  end

  def update
    @note = Note.find(params[:id])
    if @note.update(note_params)
      redirect_to :action => "show", :id => note.id
    else
      render "edit"
    end
  end

  def destroy
    note = Note.find(params[:id])
    note.destroy
    redirect_to action: :index
  end


  private

  def note_params
    params.require(:note).permit(:title, :content)
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/notes_helper.rb
module NotesHelper
  
end

app/helpers/spots_helper.rb
module SpotsHelper
  def getPercent(number) 
    if number.present?
      calPercent = number/5.to_f * 100
      percent = calPercent.round
      return percent.to_s
    else
      return 0
    end
  end
end

app/views/notes/_form.html.erb
<div class="form-container">
  <div class="backform">
    <%= link_to "＜戻る", :back %>
  </div>
    <%= form_with(model: note, local: true) do |form| %>
    <%= render 'layouts/error_messages', model: form.object %>

    <div class="title-field-container">
      <div class="form-title">
        <%= form.label :title %>
      </div>
      <div class="title-field">
        <%= form.text_field :title %>
      </div>
    </div>
    <div class="form-content">
      <%= form.label :content %>
    </div>
      <div class="content-field">
        <%= form.rich_text_area :content %>
      </div>


      <div class="actions">
        <%= form.submit "　　　投稿　　　" %>
      </div>
    <% end %>


</div>

app/views/notes/edit.html.erb
<h1>Editing Note</h1>

<%= render 'form', note: @note %>

app/views/notes/index.html.erb
<p id="notice"><%= notice %></p>

<div class="n-main">
  <div class="main-top">
    <div class="search">
      <%= form_tag({controller:"notes",action:"index"}, method: :get) do %>
        <%= text_field_tag :search %>
        <%= button_tag :type => "submit", :class =>"search-btn" do %>
          <i class="fas fa-search"></i>
        <% end %>
      <% end %>
    </div>
    <div class="new">
      <% if user_signed_in? %>
        <%= link_to new_note_path do %>
          <i class="gg-add-r"></i>
        <% end %>
      <% else %>
        <%= link_to new_user_session_path do %>
          <i class="gg-add-r"></i>
        <% end %>
      <% end %>
    </div>
  </div>

      <div class="notes-container">
        <% @notes.each do |note| %>
          <div class="note-contents">
            <div class="contents-user">
              <div class="n-userimage">
                <% if note.user.profile_image.present? %>
                  <a href="/users/<%= note.user.id %>"><%= image_tag note.user.profile_image_url, size: "30x30" %></a>
                <% else %>
                  <a href="/users/<%= note.user.id %>"><%= image_tag 'usericon.jpg' , size: "30x30" %></a>
                <% end %>
              </div>
                <div class="n-username">
                <a href="/users/<%= note.user.id %>"><%= note.user.username %></a>
              </div>
            </div>
            <div class="contents-note">
                <h3><a href="/notes/<%= note.id %>"><%= note.title %></a></h3>
            </div>
            <div class="archive">
                <i class="far fa-save"></i><%= note.archives.count %>
            </div>
          </div>
          <!-- <%= link_to "削除する", note_path(note.id), method: :delete %> -->
        <% end %>
      </div>
    <%= paginate @notes %>


</div>

app/views/notes/new.html.erb
<%= render 'form', note: @note %>

app/views/notes/show.html.erb
<p id="notice"><%= notice %></p>

<div class="n-main">
  <div class="main-top">
    <div class="n-show-user">
      <div class="n-show-userimage">
        <% if @note.user.profile_image.present? %>
          <a href="/users/<%= @note.user.id %>"><%= image_tag @note.user.profile_image_url, size: "30x30" %></a>
        <% else %>
          <a href="/users/<%= @note.user.id %>"><%= image_tag 'usericon.jpg' , size: "30x30" %></a>
        <% end %>
      </div>
      <div class="show-username">
        <a href="/users/<%= @note.user.id %>"><%= @note.user.username %></a>
      </div>
    </div>
    <div class="n-show-right">
      <div class="n-edit-delete">
        <% if user_signed_in? && current_user.id == @note.user_id %>  
          <%= link_to '編集', edit_note_path %> 
          <%= link_to "削除", note_path(@note.id), method: :delete %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="n-show-content">
    <div class="n-show-title">
      <%= @note.title %>
    </div>
    <div class="n-show-archive-container">
      <div class="n-show-archive">
        <% if user_signed_in? %>
          <% if current_user.already_archived?(@note) %>
            <%= link_to note_archive_path(@note), method: :delete do %>
              <i class="fas fa-save"></i><%= @note.archives.count %>
            <% end %>
          <% else %>
            <%= link_to note_archives_path(@note), method: :post do %>
              <i class="far fa-save"></i><%= @note.archives.count %>
            <% end %>
          <% end %>
        <% else %>
          <%= link_to new_user_session_path do %>
            <i class="far fa-save"></i><%= @note.archives.count %>
          <% end %>
        <% end %>
      </div>
    </div>
    <div class="show-contents-text">
      <%= @note.content %>
    </div>

    <div class="question-wrapper">
      <p>コメント一覧</p>
      <div class="question-contents">
        <% @questions.each do |c| %>
            <div class="question-show">
              <div class="question-left">
                <div class="question-user">
                  <div class="question-userimage">
                    <% if c.user.profile_image.present? %>
                      <a href="/users/<%= @note.user.id %>"><%= image_tag c.user.profile_image_url, size: "30x30" %></a>
                    <% else %>
                      <a href="/users/<%= @note.user.id %>"><%= image_tag 'usericon.jpg' , size: "30x30" %></a>
                    <% end %>
                  </div>
                  <div class="question-username">
                    <a href="/users/<%= @note.user.id %>"><%= c.user.username unless c.user.blank? %></a>
                  </div>
                </div>
                <div class="question-body">
                  <%= c.content %>
                </div>
              </div>
              <div class="question-right">
                <% if user_signed_in? && current_user.id == c.user_id %>  
                  <%= link_to '削除', note_question_path(@note, c), method: :delete %>
                <% end %>
              </div>
            </div>
        <% end %>
            <div class="question-form">
              <%= form_with(model: [@note, @question], local: true) do |f| %>
                <%= f.text_area :content, size: "60x2" %>
                <% if user_signed_in? %>
                  <%= button_tag type: "submit" do %>
                    <div class="submit-button">
                      <i class="far fa-comments"></i> 送信
                    </div>
                  <% end %>
                <% else %>
                  <%= link_to "送信", new_user_session_path %>
                <% end %>
              <% end %>
            </div>
      </div>
    </div>
  
  </div>
</div>