config/routes.rb
Rails.application.routes.draw do
  
  
  get 'home/index'      
  get 'home/show'

  root to: "home#index"
  

  # devise_for :users, controllers: {
  #   registrations: "users/registrations",
  # }
  devise_for :users


  resources :users do
    get :search, on: :collection
    member do
      get 'userhowto'
      get 'usernote'

      get :following, :followers
    end
  end

  resources :relationships, only: [:create, :destroy]


  resources :how_tos do
    resources :fights, only: [:create, :destroy]
    resources :advices, only: [:create, :destroy]
  end
  
  resources :spots do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end

  resources :notes do
    resources :archives, only: [:create, :destroy]
    resources :questions, only: [:create, :destroy]
  end
  

  


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/advice.rb
class Advice < ApplicationRecord
  belongs_to :user
  belongs_to :how_to

  validates :content, presence: true
end

app/models/archive.rb
class Archive < ApplicationRecord
  belongs_to :note
  belongs_to :user
  validates_uniqueness_of :note_id, scope: :user_id
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :spot

  validates :rate, presence: true
end

app/models/fight.rb
class Fight < ApplicationRecord
  belongs_to :how_to
  belongs_to :user

  validates_uniqueness_of :how_to_id, scope: :user_id
end

app/models/hashtag.rb
class Hashtag < ApplicationRecord

end

app/models/hashtag_note.rb
class HashtagNote < ApplicationRecord

end

app/models/home.rb
class Home < ApplicationRecord
  default_scope -> { order(created_at: :desc) }
end

app/models/how_to.rb
class HowTo < ApplicationRecord
  default_scope -> { order(created_at: :desc) }

  mount_uploader :image, ImageUploader
  mount_uploader :video, VideoUploader

  belongs_to :user

  has_many :fights, dependent: :destroy
  has_many :fought_users, through: :fights, source: :user
  
  has_many :advices, dependent: :destroy

  validates :title, presence: true
  validates :video, presence: true
  validates :content, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :spot
  belongs_to :user

  validates_uniqueness_of :spot_id, scope: :user_id
end

app/models/map.rb
class Map < ApplicationRecord
  
end

app/models/note.rb
class Note < ApplicationRecord
  has_rich_text :content

  belongs_to :user

  has_many :archives, dependent: :destroy
  has_many :archived_users, through: :archives, source: :user
  has_many :questions, dependent: :destroy

  validates :content, presence: true
  validates :title, presence: true
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  belongs_to :note

  validates :content, presence: true
end

app/models/relationship.rb
class Relationship < ApplicationRecord

  belongs_to :follower, class_name: "User"
  belongs_to :following, class_name: "User"
  validates :follower_id, presence: true
  validates :following_id, presence: true

end

app/models/spot.rb
class Spot < ApplicationRecord
  default_scope -> { order(created_at: :desc) }
  
  mount_uploader :image, ImageUploader
  mount_uploader :image2, ImageUploader
  mount_uploader :image3, ImageUploader

  belongs_to :user

  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user

  has_many :comments, dependent: :destroy

  has_many :post_tag_relations, dependent: :destroy
  has_many :tags, through: :post_tag_relations, dependent: :destroy


  validates :title, presence: true




end

app/models/spot_image.rb
class SpotImage < ApplicationRecord

  

end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :post_tag_relations, dependent: :destroy
  has_many :spots, through: :post_tag_relations, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :profile_image, ImageUploader
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :spots, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_spots, through: :likes, source: :spot
  has_many :comments, dependent: :destroy
  def already_liked?(spot)
    self.likes.exists?(spot_id: spot.id)
  end

  has_many :how_tos, dependent: :destroy
  has_many :fights, dependent: :destroy
  has_many :fought_how_tos, through: :fights, source: :how_to
  has_many :advices, dependent: :destroy
  def already_fought?(how_to)
    self.fights.exists?(how_to_id: how_to.id)
  end

  has_many :notes, dependent: :destroy
  has_many :archives, dependent: :destroy
  has_many :archived_notes, through: :archives, source: :note
  has_many :questions, dependent: :destroy
  def already_archived?(note)
    self.archives.exists?(note_id: note.id)
  end


  has_many :following_relationships, foreign_key: "follower_id", class_name: "Relationship", dependent: :destroy
  has_many :followings, through: :following_relationships

  has_many :follower_relationships, foreign_key: "following_id", class_name: "Relationship", dependent: :destroy
  has_many :followers, through: :follower_relationships

  def following?(other_user)
    following_relationships.find_by(following_id: other_user.id)
  end

  def follow!(other_user)
    following_relationships.create!(following_id: other_user.id)
  end

  def unfollow!(other_user)
    following_relationships.find_by(following_id: other_user.id).destroy
  end



  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable

  validates :profile, length: { maximum: 30 } 
  # validates :email, uniqueness: true
  validates :username, uniqueness: true

  # def email_required?
  #   false
  # end

  # def email_changed?
  #   false
  # end
  

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
    @spots = Spot.all.page(params[:page]).per(3)
    @how_tos = HowTo.all.page(params[:page]).per(3)
    @notes = Note.all.page(params[:page]).per(3)
  end

  def home_params
    params.require(:home).permit(:lat,:lng)
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/notes_helper.rb
module NotesHelper
  
end

app/helpers/spots_helper.rb
module SpotsHelper
  def getPercent(number) 
    if number.present?
      calPercent = number/5.to_f * 100
      percent = calPercent.round
      return percent.to_s
    else
      return 0
    end
  end
end

app/views/home/index.html.erb
<div class="home-main">
    <div class="main">
      <div class="main-content">
            <div>
              <h2>地図からスポットを探す</h2>
            </div>
            <div id='map'></div>


            <!-- js部分 -->
            <script>
                function initMap() {
                  //初期表示位置
                  let latlng = new google.maps.LatLng(35.60, 136.5);
                  //デザイン
                  let styles = [
                      {
                        stylers: [
                          { "saturation": 0 },
                          { "lightness": 0 }
                        ]
                      }
                      ];

                  let map = new google.maps.Map(document.getElementById('map'), {
                      zoom: 6.5,
                      styles: styles,
                      center: latlng
                  });
                  let transitLayer = new google.maps.TransitLayer();
                  transitLayer.setMap(map);

                  //複数マーカー ここから
                  <% @spots.each do |spot|%>
                    ( function() { 
                      let markerLatLng = new google.maps.LatLng({lat: <%= spot.lat %>, lng: <%= spot.lng %>}); // 緯度経度のデータ作成
                      let marker = new google.maps.Marker({ 
                        position: markerLatLng, 
                        map: map 
                      });
                      //マーカーをクリックしたとき、詳細情報を表示
                      let infowindow = new google.maps.InfoWindow({
                        position: markerLatLng,
                        content: "<a href='<%= spot_url(spot.id) %>' target='_blank'><%= spot.title %></a>"
                      }); //ここで詳細ページへのリンクを表示させる
                      marker.addListener('click', function() {
                        infowindow.open(map, marker);
                      });

                    })();
                  <% end %>
                  //複数マーカー ここまで  
              }
            </script>

            <script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_MAP_API_KEY'] %>&callback=initMap" async defer></script>

            
      </div>
    </div>



    <div class="home-v-main">
      <h1><%= link_to 'New Spot', spots_path %></h1>
          <div class="home-video-container">
            
            <% @spots.each do |t| %>
              <div class="home-video-contents">
                <div class="home-video-top">
                  <div class="home-contents-user">
                    <div class="home-v-userimage">
                      <% if t.user.profile_image.present? %>
                        <a href="/users/<%= t.user.id %>"><%= image_tag t.user.profile_image_url, size: "30x30" %></a>
                      <% else %>
                        <a href="/users/<%= t.user.id %>"><%= image_tag 'usericon.jpg' , size: "30x30" %></a>
                      <% end %>
                    </div>
                    <div class="home-v-username"><a href="/users/<%= t.user.id %>"><%= t.user.username %></a></div>
                  </div>
                  <div class="home-text-like">
                    <% if user_signed_in? %>
                      <% if current_user.already_liked?(t) %>
                        <%= link_to spot_like_path(id: t.id, spot_id: t.id), method: :delete do %>
                          <i class="fas fa-heart"></i><%= t.likes.count %>
                        <% end %>
                      <% else %>
                        <%= link_to spot_likes_path(id: t.id, spot_id: t.id), method: :post do %>
                          <i class="far fa-heart"></i><%= t.likes.count %>
                        <% end %>
                      <% end %>
                    <% else %>
                      <%= link_to new_user_session_path do %>
                        <%= link_to new_user_session_path do %>
                          <i class="far fa-heart"></i><%= t.likes.count %>
                        <% end %>
                      <% end %>
                    <% end %>
                  </div>
                </div>
                <div class="home-contents-video">
                  <a href="/spots/<%= t.id %>">
                    <% if t.image.present? %>
                      <%= image_tag t.image_url, size: "220x142" %>
                    <% else %>
                      <%= image_tag 'Photo.jpg', size: "220x142" %>
                    <% end %>
                  </a>
                </div>
                <div class="home-contents-text">
                  
                    
                  
                </div>
                
              </div>
            <% end %>
            
          </div>
        
    </div>




    <p id="notice"><%= notice %></p>

    <div class="home-v-main">
      <h1><%= link_to 'New Video', how_tos_path %></h1>
          <div class="home-video-container">
            
            <% @how_tos.each do |how_to| %>
              <div class="home-video-contents">
                <div class="home-video-top">
                  <div class="home-contents-user">
                    <div class="home-v-userimage">
                      <% if how_to.user.profile_image.present? %>
                        <a href="/users/<%= how_to.user.id %>"><%= image_tag how_to.user.profile_image_url, size: "30x30" %></a>
                      <% else %>
                        <a href="/users/<%= how_to.user.id %>"><%= image_tag 'usericon.jpg' , size: "30x30" %></a>
                      <% end %>
                    </div>
                    <div class="home-v-username"><a href="/users/<%= how_to.user.id %>"><%= how_to.user.username %></a></div>
                  </div>
                  <div class="home-text-fight">
                    <% if user_signed_in? %>
                      <% if current_user.already_fought?(how_to) %>
                        <%= link_to how_to_fight_path(id: how_to.id, how_to_id: how_to.id), method: :delete do %>
                          <i class="fas fa-thumbs-up"></i><%= how_to.fights.count %>
                        <% end %>
                      <% else %>
                        <%= link_to how_to_fights_path(id: how_to.id, how_to_id: how_to.id), method: :post do %>
                          <i class="far fa-thumbs-up"></i><%= how_to.fights.count %>
                        <% end %>
                      <% end %>
                    <% else %>
                      <i class="far fa-thumbs-up"></i><%= how_to.fights.count %>
                    <% end %>
                  </div>
                </div>
                <div class="home-contents-video">
                  <a href="/how_tos/<%= how_to.id %>"><%= video_tag how_to.video_url, size: "250x142" ,:controls => true ,:loop => true, muted: true if how_to.video?%></a>
                </div>
                <div class="home-contents-text">
                  
                    
                  
                </div>
              </div>
            <% end %>
          </div>
        
    </div>

  <div class="home-v-main">
    <h1><%= link_to 'New Note', notes_path %></h1>
      <div class="home-notes-container">
        <% @notes.each do |note| %>
          <div class="home-note-contents">
            <div class="home-contents-user">
              <div class="home-v-userimage">
                <% if note.user.profile_image.present? %>
                  <a href="/users/<%= note.user.id %>"><%= image_tag note.user.profile_image_url, size: "30x30" %></a>
                <% else %>
                  <a href="/users/<%= note.user.id %>"><%= image_tag 'usericon.jpg' , size: "30x30" %></a>
                <% end %>
              </div>
              <div class="home-v-username"><a href="/users/<%= note.user.id %>"><%= note.user.username %></a></div>
            </div>
            <div class="home-contents-note">
                <h3><a href="/notes/<%= note.id %>"><%= note.title %></a></h3>
            </div>
            <div class="home-archive">
                <i class="far fa-save"></i><%= note.archives.count %>
            </div>
          </div>
        <% end %>
      </div>
    
  </div>
</div>