config/routes.rb
Rails.application.routes.draw do
  
  
  get 'home/index'      
  get 'home/show'

  root to: "home#index"
  

  # devise_for :users, controllers: {
  #   registrations: "users/registrations",
  # }
  devise_for :users


  resources :users do
    get :search, on: :collection
    member do
      get 'userhowto'
      get 'usernote'

      get :following, :followers
    end
  end

  resources :relationships, only: [:create, :destroy]


  resources :how_tos do
    resources :fights, only: [:create, :destroy]
    resources :advices, only: [:create, :destroy]
  end
  
  resources :spots do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end

  resources :notes do
    resources :archives, only: [:create, :destroy]
    resources :questions, only: [:create, :destroy]
  end
  

  


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/advice.rb
class Advice < ApplicationRecord
  belongs_to :user
  belongs_to :how_to

  validates :content, presence: true
end

app/models/archive.rb
class Archive < ApplicationRecord
  belongs_to :note
  belongs_to :user
  validates_uniqueness_of :note_id, scope: :user_id
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :spot

  validates :rate, presence: true
end

app/models/fight.rb
class Fight < ApplicationRecord
  belongs_to :how_to
  belongs_to :user

  validates_uniqueness_of :how_to_id, scope: :user_id
end

app/models/hashtag.rb
class Hashtag < ApplicationRecord

end

app/models/hashtag_note.rb
class HashtagNote < ApplicationRecord

end

app/models/home.rb
class Home < ApplicationRecord
  default_scope -> { order(created_at: :desc) }
end

app/models/how_to.rb
class HowTo < ApplicationRecord
  default_scope -> { order(created_at: :desc) }

  mount_uploader :image, ImageUploader
  mount_uploader :video, VideoUploader

  belongs_to :user

  has_many :fights, dependent: :destroy
  has_many :fought_users, through: :fights, source: :user
  
  has_many :advices, dependent: :destroy

  validates :title, presence: true
  validates :video, presence: true
  validates :content, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :spot
  belongs_to :user

  validates_uniqueness_of :spot_id, scope: :user_id
end

app/models/map.rb
class Map < ApplicationRecord
  
end

app/models/note.rb
class Note < ApplicationRecord
  has_rich_text :content

  belongs_to :user

  has_many :archives, dependent: :destroy
  has_many :archived_users, through: :archives, source: :user
  has_many :questions, dependent: :destroy

  validates :content, presence: true
  validates :title, presence: true
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  belongs_to :note

  validates :content, presence: true
end

app/models/relationship.rb
class Relationship < ApplicationRecord

  belongs_to :follower, class_name: "User"
  belongs_to :following, class_name: "User"
  validates :follower_id, presence: true
  validates :following_id, presence: true

end

app/models/spot.rb
class Spot < ApplicationRecord
  default_scope -> { order(created_at: :desc) }
  
  mount_uploader :image, ImageUploader
  mount_uploader :image2, ImageUploader
  mount_uploader :image3, ImageUploader

  belongs_to :user

  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user

  has_many :comments, dependent: :destroy

  has_many :post_tag_relations, dependent: :destroy
  has_many :tags, through: :post_tag_relations, dependent: :destroy


  validates :title, presence: true




end

app/models/spot_image.rb
class SpotImage < ApplicationRecord

  

end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :post_tag_relations, dependent: :destroy
  has_many :spots, through: :post_tag_relations, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :profile_image, ImageUploader
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :spots, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_spots, through: :likes, source: :spot
  has_many :comments, dependent: :destroy
  def already_liked?(spot)
    self.likes.exists?(spot_id: spot.id)
  end

  has_many :how_tos, dependent: :destroy
  has_many :fights, dependent: :destroy
  has_many :fought_how_tos, through: :fights, source: :how_to
  has_many :advices, dependent: :destroy
  def already_fought?(how_to)
    self.fights.exists?(how_to_id: how_to.id)
  end

  has_many :notes, dependent: :destroy
  has_many :archives, dependent: :destroy
  has_many :archived_notes, through: :archives, source: :note
  has_many :questions, dependent: :destroy
  def already_archived?(note)
    self.archives.exists?(note_id: note.id)
  end


  has_many :following_relationships, foreign_key: "follower_id", class_name: "Relationship", dependent: :destroy
  has_many :followings, through: :following_relationships

  has_many :follower_relationships, foreign_key: "following_id", class_name: "Relationship", dependent: :destroy
  has_many :followers, through: :follower_relationships

  def following?(other_user)
    following_relationships.find_by(following_id: other_user.id)
  end

  def follow!(other_user)
    following_relationships.create!(following_id: other_user.id)
  end

  def unfollow!(other_user)
    following_relationships.find_by(following_id: other_user.id).destroy
  end



  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable

  validates :profile, length: { maximum: 30 } 
  # validates :email, uniqueness: true
  validates :username, uniqueness: true

  # def email_required?
  #   false
  # end

  # def email_changed?
  #   false
  # end
  

end

app/controllers/how_tos_controller.rb
class HowTosController < ApplicationController
  layout 'how_to'
  
  def index
    if params[:search] == nil
      @how_tos= HowTo.all.page(params[:page]).per(15)
    elsif params[:search] == ''
      @how_tos= HowTo.all.page(params[:page]).per(15)
    else
      @how_tos = HowTo.where("title LIKE ? ",'%' + params[:search] + '%').or(HowTo.where("content LIKE ? ", "%" + params[:search] + "%")).page(params[:page]).per(15)
    end
  end

  def new
    @how_to = HowTo.new
  end

  def create
    @how_to = HowTo.new(how_to_params)
    @how_to.user_id = current_user.id
    if @how_to.save
      redirect_to :action => "index"
    else
      render "new"
    end
  end

  def show
    @how_to = HowTo.find(params[:id])
    @advices = @how_to.advices
    @advice = Advice.new
  end

  def edit
    @how_to = HowTo.find(params[:id])
  end

  def update
    @how_to = HowTo.find(params[:id])
    if @how_to.update(how_to_params)
      redirect_to :action => "show", :id => how_to.id
    else
      render "edit"
    end
  end

  def destroy
    how_to = HowTo.find(params[:id])
    how_to.destroy
    redirect_to action: :index
  end

  

  private

  def how_to_params
    params.require(:how_to).permit(:title, :content, :image, :video)
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/how_tos_helper.rb
module HowTosHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/notes_helper.rb
module NotesHelper
  
end

app/views/how_tos/_form.html.erb
<div class="form-container">
  <div class="backform">
    <%= link_to "＜戻る", :back %>
  </div>
  <div class="form-contents">

      <%= form_with(model: how_to, local: true) do |form| %>
      <%= render 'layouts/error_messages', model: form.object %>
        
        <div class="title-field-container">
          <div class="form-title">
            <%= form.label :title %>
          </div>
          <div class="title-field">
            <%= form.text_field :title %>
          </div>
        </div>
        <div class="content-field-container">
          <div class="form-content">
            <%= form.label :content %>
          </div>
          <div class="content-field">
            <%= form.text_area :content, :size => "67x5" %>
          </div>
        </div>
        <div class="video-container">
          <div class="form-video">
            <%= form.label :video %>
          </div>
          <div class="video-field">
            <%= form.file_field :video %>
          </div>
        </div>

          <div class="actions">
            <%= form.submit "　　　投稿　　　" %>
          </div>
      <% end %>

  </div>
</div>

app/views/how_tos/edit.html.erb
<%= render 'form', how_to: @how_to %>

app/views/how_tos/index.html.erb
<p id="notice"><%= notice %></p>

<div class="v-main">
  <div class="main-top">
    <div class="search">
      <%= form_tag({controller:"how_tos",action:"index"}, method: :get) do %>
        <%= text_field_tag :search %>
        <%= button_tag :type => "submit", :class =>"search-btn" do %>
          <i class="fas fa-search"></i>
        <% end %>
      <% end %>
    </div>
    <div class="new">
      <% if user_signed_in? %>
        <%= link_to new_how_to_path do %>
          <i class="gg-add-r"></i>
        <% end %>
      <% else %>
        <%= link_to new_user_session_path do %>
          <i class="gg-add-r"></i>
        <% end %>
      <% end %>
    </div>
  </div>
      <div class="video-container">
        <% @how_tos.each do |how_to| %>
          <div class="video-contents">
            <div class="contents-user">
              <div class="v-userimage">
                  <% if how_to.user.profile_image.present? %>
                    <a href="/users/<%= how_to.user.id %>"><%= image_tag how_to.user.profile_image_url, size: "30x30" %></a>
                  <% else %>
                    <a href="/users/<%= how_to.user.id %>"><%= image_tag 'usericon.jpg' , size: "30x30" %></a>
                  <% end %>
              </div>
              <div class="v-username"><a href="/users/<%= how_to.user.id %>"><%= how_to.user.username %></a></div>
            </div>
            <div class="contents-video">
              <a href="/how_tos/<%= how_to.id %>"><%= video_tag how_to.video_url, size: "600x337" ,:controls => true ,:loop => true, autoplay: true , muted: true if how_to.video?%></a>
            </div>
            <div class="contents-text">
              <div class="v-contents-text">
                <div class="v-text-title">
                  <a href="/how_tos/<%= how_to.id %>"><%= how_to.title %></a>
                </div>
                <div class="v-text-contents">
                  <a href="/how_tos/<%= how_to.id %>"><%= how_to.content %></a>
                </div>
              </div>
                <div class="text-fight">
                  <% if user_signed_in? %>
                    <% if current_user.already_fought?(how_to) %>
                      <%= link_to how_to_fight_path(id: how_to.id, how_to_id: how_to.id), method: :delete do %>
                        <i class="fas fa-thumbs-up"></i><%= how_to.fights.count %>
                      <% end %>
                    <% else %>
                      <%= link_to how_to_fights_path(id: how_to.id, how_to_id: how_to.id), method: :post do %>
                        <i class="far fa-thumbs-up"></i><%= how_to.fights.count %>
                      <% end %>
                    <% end %>
                  <% else %>
                    <i class="far fa-thumbs-up"></i><%= how_to.fights.count %>
                  <% end %>
                </div>
              
            </div>
          </div>
        <% end %>
      </div>
    <%= paginate @how_tos %>
</div>

app/views/how_tos/new.html.erb
<%= render 'form', how_to: @how_to %>

app/views/how_tos/show.html.erb
<p id="notice"><%= notice %></p>

<div class="v-show-main">
  <div class="v-show-top">
    <div class="v-show-user">
      <div class="v-show-userimage">
          <% if @how_to.user.profile_image.present? %>
            <a href="/users/<%= @how_to.user.id %>"><%= image_tag @how_to.user.profile_image_url, size: "30x30" %></a>
          <% else %>
            <%= image_tag 'usericon.jpg' , size: "30x30" %>
          <% end %>
      </div>
      <div class="v-show-username">
        <a href="/users/<%= @how_to.user.id %>"><%= @how_to.user.username %></a>
      </div>
    </div>
    <div class="v-show-fight">
          <% if user_signed_in? %>
              <% if current_user.already_fought?(@how_to) %>
                  <%= link_to how_to_fight_path(@how_to), method: :delete do %>
                    <i class="fas fa-thumbs-up"></i><%= @how_to.fights.count %>
                  <% end %>
              <% else %>
                  <%= link_to how_to_fights_path(@how_to), method: :post do %>
                  <i class="far fa-thumbs-up"></i><%= @how_to.fights.count %>
                  <% end %>
              <% end %>
          <% else %>
              <i class="far fa-fire-alt"></i><%= @how_to.fights.count %>
          <% end %>
    </div>
  </div>
  <div class="show-video">
      <%= video_tag @how_to.video_url, size: "700x400" ,:controls => true ,:loop => true, autoplay: true , muted: true if @how_to.video?%>
  </div>
  <div class="v-show-text">
    <duv class="v-show-text-left">
      <div class="v-show-text-title">
        <%= @how_to.title %>
      </div>
      <div class="v-show-text-content">
        <%= @how_to.content %>
      </div>
    </duv>
    <div class="show-edit-delete">
          <% if user_signed_in? && current_user.id == @how_to.user_id %>  
            <%= link_to '編集', edit_how_to_path(@how_to) %> 
            <%= link_to "削除", how_to_path, method: :delete %>
          <% end %>
    </div>
  </div>

          <!-- <h2>いいねしたユーザー</h2>
          <% @how_to.fought_users.each do |user| %>
            <li><%= user.username %></li>
          <% end %> -->

  <div class="advice-wrapper">
      <p>コメント一覧</p>
      <div class="advice-contents">
        <% @advices.each do |c| %>
            <div class="advice-show">
              <div class="advice-left">
                <div class="advice-user">
                  <div class="advice-userimage">
                    <% if c.user.profile_image.present? %>
                      <a href="/users/<%= @how_to.user.id %>"><%= image_tag c.user.profile_image_url, size: "30x30" %></a>
                    <% else %>
                      <a href="/users/<%= @how_to.user.id %>"><%= image_tag 'usericon.jpg' , size: "30x30" %></a>
                    <% end %>
                  </div>
                  <div class="advice-username">
                    <a href="/users/<%= @how_to.user.id %>"><%= c.user.username unless c.user.blank? %></a>
                  </div>
                </div>
                <div class="advice-body">
                  <%= c.content %>
                </div>
              </div>
              <div class="advice-right">
                <% if user_signed_in? && current_user.id == c.user_id %>  
                  <%= link_to '削除', how_to_advice_path(@how_to, c), method: :delete %>
                <% end %>
              </div>
            </div>
        <% end %>
            <div class="advice-form">
              <%= form_with(model: [@how_to, @advice], local: true) do |f| %>
                <%= f.text_area :content, size: "60x2" %>
                <% if user_signed_in? %>
                  <%= button_tag type: "submit" do %>
                    <div class="submit-button">
                      <i class="far fa-comments"></i> 送信
                    </div>
                  <% end %>
                <% else %>
                  <%= link_to "送信", new_user_session_path %>
                <% end %>
              <% end %>
            </div>
      </div>
  </div>
</div>